# json文件路径
#jsonPath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\json\15.YJ160-11(T2-17X)_t3.json
jsonPath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\json\15.集团版YJ160-11(T2-17X)_t3.json
#jsonPath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\json\3-20.json

#jsonPath: D:\项目-代码和数据仅在本地\CAD\解析dxf\桌面上的CAD文件夹和文件\CAD相关_桌面临时\贾振威\1208\01_WSP-2429A1.json
#jsonPath: D:\项目-代码和数据仅在本地\CAD\解析dxf\桌面上的CAD文件夹和文件\CAD相关_桌面临时\刘博\1210\01_WSP-2429A1.json
#jsonPath: D:/项目-代码和数据仅在本地/CAD/解析dxf/桌面上的CAD文件夹和文件/CAD相关_桌面临时/王婷/1228/茂名碧桂园天钻2#楼.json

#jsonPath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\json\门窗新图元模板参考.json
#jsonPath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\json\门窗新图元模板参考_画了一个矩形框.json

# 是否保留缓存
isSaveCache: False
# 缓存文件夹路径
cache: ../cache #如果不写，则是./cache；如果写一个相对路径，则是相对于这个.yaml文件的；

# 调色盘 #各种颜色的RGB值
colorMap:
  r: [255, 0, 0]
  g: [0, 255, 0]
  b: [0, 0, 255]
  m: [255, 0, 255]
  white: [255, 255, 255]
  yellow: [255, 255, 0]
  orange: [255, 128, 0]
  pink: [255, 192, 203]
  violet: [138, 43, 226]
  black: [0, 0, 0]
  SlateBlue: [106, 90, 205]
  SaddleBrown: [139, 69, 19]
  grassgreen: [107, 142, 35]
  chocolate: [210, 105, 30]
  mazarine: [25, 25, 112]
  TurquoiseBlue: [0, 199, 140]

# 绘图分辨率
restoreScaleFactor: 0.1 #浮点型，表示pygame的尺寸相对于CAD尺寸的比例，过小不清楚，过大会报错，不能使用科学计数法 #10.0 * 1e-2
resotreResolution: #3000.0 # 5000.0 #1500.0 ## 可以是浮点型 #该变量为空时，restoreScaleFactor生效；该变量不为空时，restoreScaleFactor不生效；#保证在Pinter之前不会用到restoreScaleFactor #保证在Pinter之外不会用到restoreScaleFactor
# 边框冗余
redundantBorder: 0 # 15 ##10 #左右加起来或者上下加起来，冗余这么多像素
# 是否保存图像
isSaveFig: True #False # #布尔型
# 保存图像路径
savePath: D:\cad_draw_engine_cpp\cad-graphics-engine-cpp\AtuoCADDataAnalysisPyCADCpp\figs #./figs #"./figs" #字符串 #默认为 桌面上的figs 或者 /home/user/figs
# 保存图像文件名
saveFileName: #字符串 #默认为用时间命名的png

# 是否打印进度信息的开关
verbose: False # True # #

# 字号 或者 文字的分辨率
fontsize: 100 #整型
# 字体文件路径
fontfile: #字符串 #默认为一个simsun.ttc字体文件路径
# 关于是否画文本的所有开关
isPlotText: #hard-coded
  # 是否画文本
  plotTexts: True # False # #布尔型
  # 是否画attributes
  plotAttributes: True # False # #布尔型
# 关于是否画文本框的所有开关
isPlotBox:
  # 是否画文本框
  plotTextsBox: True # False # #布尔型
  # 是否attributes框
  plotAttributesBox: True # False # #布尔型

# 指定 应排除的 空的文本信息 的形式 #{"\"\"", "\'\'", "\""}
vacantTextInfo: ["''", '""', "'", '"']
isExcludeVacantTextInfo: True # False # # #画图 以及 画图搜集文本类信息的时候，是否排除空字符串

# 特征文件路径 #用于查找筛选条件
featurefile: #字符串 #默认为一个feature.csv字体文件路径

# 筛选的各个标签之间是 交集 还是 并集 #标签是指blockHandlesPedigree, layers, BRHandles等关键字 #指控
judgementsInterOrUnion: Inter #Union # #字符串

# 白名单与黑名单筛选标签 #示例：["qwe", "rty", "123", ...]
judgements:
  blockHandlesPedigree:
    wanted:  [""] # 筛选Block #"[639F]"
    blackList: [""] #黑名单
  layers:
    wanted:  [""] #"活动" #"签" #Y-云图签字 #墙 #"DOTE", "AXIS" #"墙", "WALL" A-墙体 #WINDOW
    blackList: [""] #黑名单 #轴线 #5-改造版-家具 #A-墙体-结构墙柱", "A-墙体-结构墙柱填充 #"轴线-隔墙",'柱'
  BRHandles:
    wanted:  [""] # Block Reference Handle #[2010]
    blackList: [""] #黑名单

# isFromHatchs
isFromHatchs: False # True # #如果此项为True，则仅选取带有hatch的eIns

# 区域筛选 的 区域 以及 内外选择标志量
regions: [] #[[460960.587, 89527.829], [463633.59, 96084.393]] # 筛选区域矩形的顶点 #格式：[[xmin, ymin], [xmax, ymax]] #regions: [[17, 7], [84117, 59407]] # 筛选区域矩形的顶点 #格式：[[xmin, ymin], [xmax, ymax]]
insideOrOutside: Inside #Outside #

# 优先级最高的白名单（依类型）
whitelistForType: [""] #["texts", "attributes"]
